UPDATE routes_reference SET km_normal = 0, km_special = 130, notes = 'Херсонская спецзона', updated_at = NOW() WHERE id = 8;
UPDATE routes_reference SET km_normal = 0, km_special = 75, notes = 'Запорожская спецзона', updated_at = NOW() WHERE id = 7;
UPDATE routes_reference SET km_normal = 0, km_special = 55, notes = 'ЛНР спецзона', updated_at = NOW() WHERE id = 13;
UPDATE routes_reference SET km_normal = 0, km_special = 60, notes = 'ЛНР спецзона', updated_at = NOW() WHERE id = 14;
UPDATE routes_reference SET km_normal = 0, km_special = 120, notes = 'ДНР-Крым спецзона', updated_at = NOW() WHERE id IN (44, 121);
UPDATE routes_reference SET km_normal = 870, km_special = 90, notes = 'Москва-ДНР', updated_at = NOW() WHERE id IN (24, 217);
UPDATE routes_reference SET km_normal = 900, km_special = 100, notes = 'Москва-Херсон', updated_at = NOW() WHERE id IN (27, 225);
UPDATE routes_reference SET km_normal = 125, km_special = 240, notes = 'Крым-Херсон', updated_at = NOW() WHERE id IN (98, 134);
UPDATE routes_reference SET km_normal = 80, km_special = 240, notes = 'Крым-Херсон', updated_at = NOW() WHERE id IN (108, 135);
UPDATE routes_reference SET km_normal = 50, km_special = 240, notes = 'Крым-Херсон', updated_at = NOW() WHERE id IN (115, 133);
UPDATE routes_reference SET km_normal = 125, km_special = 120, notes = 'Крым-Геническ', updated_at = NOW() WHERE id IN (99, 137);
UPDATE routes_reference SET km_normal = 80, km_special = 120, notes = 'Крым-Геническ', updated_at = NOW() WHERE id = 109;
UPDATE routes_reference SET km_normal = 125, km_special = 380, notes = 'Крым-ДНР', updated_at = NOW() WHERE id IN (104, 143);
UPDATE routes_reference SET km_normal = 125, km_special = 310, notes = 'Крым-Мариуполь', updated_at = NOW() WHERE id IN (105, 145);
UPDATE routes_reference SET km_normal = 125, km_special = 480, notes = 'Крым-ЛНР', updated_at = NOW() WHERE id = 106;
UPDATE routes_reference SET km_normal = 80, km_special = 380, notes = 'Крым-ДНР', updated_at = NOW() WHERE id = 112;
UPDATE routes_reference SET km_normal = 80, km_special = 320, notes = 'Крым-Мариуполь', updated_at = NOW() WHERE id = 113;
UPDATE routes_reference SET km_normal = 50, km_special = 310, notes = 'Крым-Мариуполь', updated_at = NOW() WHERE id IN (122, 144);
UPDATE routes_reference SET km_normal = 50, km_special = 470, notes = 'Крым-ЛНР', updated_at = NOW() WHERE id = 123;
UPDATE routes_reference SET km_normal = 50, km_special = 200, notes = 'Крым-Энергодар', updated_at = NOW() WHERE id = 119;
UPDATE routes_reference SET km_normal = 155, km_special = 120, notes = 'Керчь-Геническ', updated_at = NOW() WHERE id = 125;
UPDATE routes_reference SET km_normal = 155, km_special = 90, notes = 'Керчь-Бердянск', updated_at = NOW() WHERE id = 127;
UPDATE routes_reference SET km_normal = 155, km_special = 150, notes = 'Керчь-Мариуполь', updated_at = NOW() WHERE id = 128;
UPDATE routes_reference SET km_normal = 360, km_special = 280, notes = 'Краснодар-Херсон', updated_at = NOW() WHERE id = 170;
UPDATE routes_reference SET km_normal = 350, km_special = 330, notes = 'Белгород-Херсон', updated_at = NOW() WHERE id = 257;
UPDATE routes_reference SET km_normal = 430, km_special = 330, notes = 'Курск-Херсон', updated_at = NOW() WHERE id = 271;
UPDATE routes_reference SET km_normal = 0, km_special = 240, notes = 'Херсон-Мелитополь спецзона', updated_at = NOW() WHERE id IN (146, 152);
UPDATE routes_reference SET km_normal = 0, km_special = 320, notes = 'Херсон-Бердянск спецзона', updated_at = NOW() WHERE id IN (147, 156);
